-- 122_add_gst_to_assets.sql
ALTER TABLE assets 
ADD COLUMN IF NOT EXISTS is_gst_purchase BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst_no VARCHAR(20),
ADD COLUMN IF NOT EXISTS bill_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS created_by INTEGER;
