-- 123_add_sale_gst_to_assets.sql
ALTER TABLE assets 
ADD COLUMN IF NOT EXISTS sale_buyer_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS sale_buyer_gst VARCHAR(20),
ADD COLUMN IF NOT EXISTS sale_is_gst BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sale_taxable_amount NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sale_tax_amount NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sale_invoice_no VARCHAR(50);
