import { api } from '@/lib/axios'

/** Full endpoint surface for the Inventory module — extracted from the source app (Build Spec §8). */
export const inventoryApi = {
  getBankAccounts: () => api.get('/api/bank-accounts').then((r) => r.data),
  getDebitNotesVendor: (id: string | number) => api.get(`/api/debit-notes/vendor/${id}`).then((r) => r.data),
  getDebitNotesItems: (id: string | number) => api.get(`/api/debit-notes/${id}/items`).then((r) => r.data),
  getDocumentsNextPO: () => api.get('/api/documents/next/PO').then((r) => r.data),
  getEmployeesProfile: () => api.get('/api/employees/profile').then((r) => r.data),
  getFinanceReconciliationBankUnconsumedDebits: () => api.get('/api/finance/reconciliation/bank/unconsumed-debits').then((r) => r.data),
  getMasterBanks: () => api.get('/api/master/banks').then((r) => r.data),
  getMasterBrands: () => api.get('/api/master/brands').then((r) => r.data),
  getMasterCategories: () => api.get('/api/master/categories').then((r) => r.data),
  getMasterHsn: () => api.get('/api/master/hsn').then((r) => r.data),
  getMasterTaxes: () => api.get('/api/master/taxes').then((r) => r.data),
  getMasterVendorAddresses: () => api.get('/api/master/vendor-addresses').then((r) => r.data),
  getProducts: () => api.get('/api/products').then((r) => Array.isArray(r.data) ? r.data : (r.data?.data || [])),
  getProductsTemplateData: () => api.get('/api/products/template-data').then((r) => r.data),
  getPurchaseInvoices: () => api.get('/api/purchase-invoices').then((r) => r.data),
  getPurchaseOrders: () => api.get('/api/purchase-orders').then((r) => r.data),
  getPurchaseOrders2: (id: string | number) => api.get(`/api/purchase-orders/${id}`).then((r) => r.data),
  getPurchaseOrders3: (selectedOptionValue: string | number) => api.get(`/api/purchase-orders/${selectedOptionValue}`).then((r) => r.data),
  getStockAdjustBatches: (selectedOptionValue: string | number) => api.get(`/api/stock/adjust/batches/${selectedOptionValue}`).then((r) => r.data),
  getVendorPaymentsLedger: (id: string | number) => api.get(`/api/vendor-payments/ledger/${id}`).then((r) => r.data),
  getVendors: () => api.get('/api/vendors').then((r) => r.data),
  getVendorsAddresses: (id: string | number) => api.get(`/api/vendors/${id}/addresses`).then((r) => r.data),
  createPurchaseInvoices: (payload: any) => api.post('/api/purchase-invoices', payload).then((r) => r.data),
  createPurchaseInvoicesReverse: (id: string | number, payload: any = {}) => api.post(`/api/purchase-invoices/${id}/reverse`, payload).then((r) => r.data),
  createPurchaseOrders: (payload: any) => api.post('/api/purchase-orders', payload).then((r) => r.data),
  updatePurchaseOrders: (selectedPOId: string | number, payload: any = {}) => api.put(`/api/purchase-orders/${selectedPOId}`, payload).then((r) => r.data),
}
